from profile_HMM import profile_HMM_sequence_alignment


profile_HMM_sequence_alignment(
    "YUURIYUPEERITEIOYRTPOPOPYWIOURTIPRIQTIQEUUIEUERWUWQEWYIUOWPPRUYUEEIRTWUUQWQTROWTYPUEPWEEEQIWRT",
    0.25,
    0.04,
    "QWERTYUIOP",
    [
        "YUIRQYUPPEORIEIOPPYRTPOPPOPPOIQWR-TRIRI-QTQ-UPQUUTEEUURQQUWIQEWWIUOWPPRUTEUIIUYUQWUTRWTPWE-PEEEQIWRT",
        "YUUIRIYUPPERITEIOPYRTPOPPOPPWIQRTIIRIQTPIU-PTQUOUIEEUURETPRWQEWWEUOWPPR-UTEYIIUUQWUTRWTPPWEPEEPQIWRT",
        "YUUIRIYPPERITEIOPERTPOPPTOPPIWIRWRIIIRIQTIUPQUU-IEEUURTQUWQWYWIUOYTPPPUPT-UIITUIEQWUQTRWTPPEPEEQTIWR",
        "YUUIRIYOUPP-ERI-TEIOPYTPOPPOPPW-IURTIQR-YIQ-IUPQ-UUIEEURTOUWEEWWIUWPP-PRUTE-UIITUQW-UE-RWTPIEEWQIWRT",
        "YUUIRIYTUPEREITEIOIYRTPOUPUPPWIUWRTIRIQTIUP-QUUQEEUURTQOUWQEWWIUOWPPRUWEUIIT-UU-QWUTRWTPWETPEEEQIWRT",
        "UYIUUIREUPEERIOEIEPYRTPOPUIOPPWOUYWTIIWI-QEIUPQUIEE-UUWRTQUWQEWWIUOWPPUOYOUIQITEUQWUTRWTPWEPEEEQIWRT",
        "YUUIRIPUPPERITEIOP-RTPOPPO-QPPWIUWRTIIRI-QTIUPQUIEEUURPYUWQEWWI-UOWPPPUPEUIITUUQWUTRWTPW-EP-EERQIWRT",
        "YUUI-RIUPPRTEQIWPYRTEP-OPQ-PRPPEIWRTII-RIQTUIUP-UUIEOURTUWQEWYIOWPPORITIUEIIYUUQWUTIRWT-PWEPE-EYQIWT",
        "YIUYYRIYUPERUITETIOPYRRTPOWPQ-POPPWUPWRTIRQQUYQUUIEIEUQRTQWQEWWI-UOYPYOE-UIITUEUQWUTRWTPWE-PEEQIWRRW",
        "YUUEIYRP-PERIT-EPOPYROPEPPOPWIUWRTIIPIQT-IUPOUUIET-URTQ-UWQE-W-WIUWPP-UTEQIITUUQWYTRWTPWE-PEE-EQIWRT",
    ],
)
